import { StyleSheet, Platform, Dimensions } from "react-native";
const maxHeight = Dimensions.get('window').height
const maxWidth = Dimensions.get('window').width


export default StyleSheet.create({

    container: {
        flex: 1,
        backgroundColor: "#f1f1f1",
        // paddingBottom: Platform.OS === 'ios' ? 50 : 0,
    },
    flex: { flex: 1 },
    colorP: { color: "#c62910" },
    colorS: { color: "#8d1e0d" },
    colorT: { color: "#BDBDBD" },
    colorGrey: { color: "#828282" },
    colorW: { color: "#FFF" },
    colorD: { color: "#EB5757" },
    colorB: { color: "#000" },
    colorWarn: { color: "#FFCF4E" },
    colorSuccess: { color: "#33D37A" },
    colorI: { color: "#28BBD5" },

    bgP: { backgroundColor: "#c62910" },
    bgPT: { backgroundColor: 'rgba(142, 143, 236, 0.7)' },
    bgS: { backgroundColor: "#8d1e0d" },
    bgT: { backgroundColor: "#BDBDBD" },
    bgW: { backgroundColor: "#FFF" },
    bgB: { backgroundColor: "#000" },
    bgDanger: { backgroundColor: "#EB5757" },
    bgSuccess: { backgroundColor: "#33D37A" },
    bgWarn: { backgroundColor: "#FFCF4E" },
    bgI: { backgroundColor: "#28BBD5" },

    screen_W: { width: maxWidth },
    screen_H: { height: maxHeight },
    /////////////////////////////////
    w_5: { width: "5%", },
    w_10: { width: "10%" },
    w_15: { width: "15%" },
    w_18: { width: "18%" },
    w_20: { width: "20%" },
    w_25: { width: "25%" },
    w_30: { width: "30%" },
    w_33: { width: "33.33%" },
    w_35: { width: "35%" },
    w_40: { width: "40%" },
    w_45: { width: "45%" },
    w_48: { width: "48%" },
    w_49: { width: "49%" },
    w_50: { width: "50%" },
    w_55: { width: "55%" },
    w_60: { width: "60%" },
    w_65: { width: "65%" },
    w_70: { width: "70%" },
    w_75: { width: "75%" },
    w_80: { width: "80%" },
    w_85: { width: "85%" },
    w_75: { width: "75%" },
    w_90: { width: "90%" },
    w_95: { width: "95%" },
    w_100: { width: "100%" },

    h_5: { height: "5%" },
    h_10: { height: "10%" },
    h_15: { height: "15%" },
    h_20: { height: "20%" },
    h_25: { height: "25%" },
    h_30: { height: "30%" },
    h_35: { height: "35%" },
    h_40: { height: "40%" },
    h_50: { height: "50%" },
    h_55: { height: "55%" },
    h_60: { height: "60%" },
    h_65: { height: "65%" },
    h_70: { height: "70%" },
    h_75: { height: "75%" },
    h_80: { height: "80%" },
    h_75: { height: "75%" },
    h_90: { height: "90%" },
    h_95: { height: "95%" },
    h_100: { height: "100%" },
    /////////////////////////////////

    p4: { padding: 4 },
    p8: { padding: 8 },
    p16: { padding: 16 },
    p24: { padding: 24 },
    p32: { padding: 32 },
    p40: { padding: 40 },
    p48: { padding: 48 },
    p64: { padding: 64 },
    p96: { padding: 96 },

    pT4: { paddingTop: 4 },
    pT8: { paddingTop: 8 },
    pT16: { paddingTop: 16 },
    pT24: { paddingTop: 24 },
    pT32: { paddingTop: 32 },
    pT40: { paddingTop: 40 },
    pT48: { paddingTop: 48 },
    pT64: { paddingTop: 64 },
    pT96: { paddingTop: 96 },

    pL4: { paddingLeft: 4 },
    pL8: { paddingLeft: 8 },
    pL16: { paddingLeft: 16 },
    pL24: { paddingLeft: 24 },
    pL32: { paddingLeft: 32 },
    pL40: { paddingLeft: 40 },
    pL48: { paddingLeft: 48 },
    pL64: { paddingLeft: 64 },
    pL96: { paddingLeft: 96 },

    pR4: { paddingRight: 4 },
    pR8: { paddingRight: 8 },
    pR16: { paddingRight: 16 },
    pR24: { paddingRight: 24 },
    pR32: { paddingRight: 32 },
    pR40: { paddingRight: 40 },
    pR48: { paddingRight: 48 },
    pR64: { paddingRight: 64 },
    pR96: { paddingRight: 96 },

    pB4: { paddingBottom: 4 },
    pB8: { paddingBottom: 8 },
    pB16: { paddingBottom: 16 },
    pB24: { paddingBottom: 24 },
    pB32: { paddingBottom: 32 },
    pB40: { paddingBottom: 40 },
    pB48: { paddingBottom: 48 },
    pB64: { paddingBottom: 64 },
    pB96: { paddingBottom: 96 },

    pV4: { paddingVertical: 4 },
    pV8: { paddingVertical: 8 },
    pV16: { paddingVertical: 16 },
    pV24: { paddingVertical: 24 },
    pV32: { paddingVertical: 32 },
    pV40: { paddingVertical: 40 },
    pV48: { paddingVertical: 48 },
    pV64: { paddingVertical: 64 },
    pV96: { paddingVertical: 96 },

    pH4: { paddingHorizontal: 4 },
    pH8: { paddingHorizontal: 8 },
    pH16: { paddingHorizontal: 16 },
    pH24: { paddingHorizontal: 24 },
    pH32: { paddingHorizontal: 32 },
    pH40: { paddingHorizontal: 40 },
    pH48: { paddingHorizontal: 48 },
    pH64: { paddingHorizontal: 64 },
    pH96: { paddingHorizontal: 96 },

    /////////////////////////////////

    p5: { padding: 5 },
    p10: { padding: 10 },
    p15: { padding: 15 },
    p20: { padding: 20 },
    p25: { padding: 25 },
    p30: { padding: 30 },
    p35: { padding: 35 },
    p40: { padding: 40 },
    p50: { padding: 50 },
    p60: { padding: 60 },
    p70: { padding: 70 },
    p80: { padding: 80 },
    p90: { padding: 90 },
    p100: { padding: 100 },

    pT5: { paddingTop: 5 },
    pT10: { paddingTop: 10 },
    pT15: { paddingTop: 15 },
    pT20: { paddingTop: 20 },
    pT25: { paddingTop: 25 },
    pT30: { paddingTop: 30 },
    pT35: { paddingTop: 35 },
    pT40: { paddingTop: 40 },
    pT50: { paddingTop: 50 },
    pT60: { paddingTop: 60 },
    pT70: { paddingTop: 70 },
    pT80: { paddingTop: 80 },
    pT90: { paddingTop: 90 },
    pT100: { paddingTop: 100 },

    pB5: { paddingBottom: 5 },
    pB10: { paddingBottom: 10 },
    pB15: { paddingBottom: 15 },
    pB20: { paddingBottom: 20 },
    pB25: { paddingBottom: 25 },
    pB30: { paddingBottom: 30 },
    pB35: { paddingBottom: 35 },
    pB40: { paddingBottom: 40 },
    pB50: { paddingBottom: 50 },
    pB60: { paddingBottom: 60 },
    pB70: { paddingBottom: 70 },
    pB80: { paddingBottom: 80 },
    pB90: { paddingBottom: 90 },
    pB100: { paddingBottom: 100 },

    pL5: { paddingLeft: 5 },
    pL10: { paddingLeft: 10 },
    pL15: { paddingLeft: 15 },
    pL20: { paddingLeft: 20 },
    pL25: { paddingLeft: 25 },
    pL30: { paddingLeft: 30 },
    pL35: { paddingLeft: 35 },
    pL40: { paddingLeft: 40 },
    pL50: { paddingLeft: 50 },
    pL60: { paddingLeft: 60 },
    pL70: { paddingLeft: 70 },
    pL80: { paddingLeft: 80 },
    pL90: { paddingLeft: 90 },
    pL100: { paddingLeft: 100 },

    pR5: { paddingRight: 5 },
    pR10: { paddingRight: 10 },
    pR15: { paddingRight: 15 },
    pR20: { paddingRight: 20 },
    pR25: { paddingRight: 25 },
    pR30: { paddingRight: 30 },
    pR35: { paddingRight: 35 },
    pR40: { paddingRight: 40 },
    pR50: { paddingRight: 50 },
    pR60: { paddingRight: 60 },
    pR70: { paddingRight: 70 },
    pR80: { paddingRight: 80 },
    pR90: { paddingRight: 90 },
    pR100: { paddingRight: 100 },

    pV5: { paddingVertical: 5 },
    pV10: { paddingVertical: 10 },
    pV15: { paddingVertical: 15 },
    pV20: { paddingVertical: 20 },
    pV25: { paddingVertical: 25 },
    pV30: { paddingVertical: 30 },
    pV35: { paddingVertical: 35 },
    pV40: { paddingVertical: 40 },
    pV50: { paddingVertical: 50 },
    pV60: { paddingVertical: 60 },
    pV70: { paddingVertical: 70 },
    pV80: { paddingVertical: 80 },
    pV90: { paddingVertical: 90 },
    pV100: { paddingVertical: 100 },

    pH5: { paddingHorizontal: 5 },
    pH10: { paddingHorizontal: 10 },
    pH15: { paddingHorizontal: 15 },
    pH20: { paddingHorizontal: 20 },
    pH25: { paddingHorizontal: 25 },
    pH30: { paddingHorizontal: 30 },
    pH35: { paddingHorizontal: 35 },
    pH40: { paddingHorizontal: 40 },
    pH50: { paddingHorizontal: 50 },
    pH60: { paddingHorizontal: 60 },
    pV70: { paddingHorizontal: 70 },
    pV80: { paddingHorizontal: 80 },
    pV90: { paddingHorizontal: 90 },
    pH100: { paddingHorizontal: 100 },

    ///////////////////////////////////////////////

    m4: { margin: 4 },
    m8: { margin: 8 },
    m16: { margin: 16 },
    m24: { margin: 24 },
    m32: { margin: 32 },
    m40: { margin: 40 },
    m48: { margin: 48 },
    m64: { margin: 64 },
    m96: { margin: 96 },

    mT4: { marginTop: 4 },
    mT8: { marginTop: 8 },
    mT16: { marginTop: 16 },
    mT24: { marginTop: 24 },
    mT32: { marginTop: 32 },
    mT40: { marginTop: 40 },
    mT48: { marginTop: 48 },
    mT64: { marginTop: 64 },
    mT96: { marginTop: 96 },

    mL4: { marginLeft: 4 },
    mL8: { marginLeft: 8 },
    mL16: { marginLeft: 16 },
    mL24: { marginLeft: 24 },
    mL32: { marginLeft: 32 },
    mL40: { marginLeft: 40 },
    mL48: { marginLeft: 48 },
    mL64: { marginLeft: 64 },
    mL96: { marginLeft: 96 },

    mR4: { marginRight: 4 },
    mR8: { marginRight: 8 },
    mR16: { marginRight: 16 },
    mR24: { marginRight: 24 },
    mR32: { marginRight: 32 },
    mR40: { marginRight: 40 },
    mR48: { marginRight: 48 },
    mR64: { marginRight: 64 },
    mR96: { marginRight: 96 },

    mB4: { marginBottom: 4 },
    mB8: { marginBottom: 8 },
    mB16: { marginBottom: 16 },
    mB24: { marginBottom: 24 },
    mB32: { marginBottom: 32 },
    mB40: { marginBottom: 40 },
    mB48: { marginBottom: 48 },
    mB64: { marginBottom: 64 },
    mB96: { marginBottom: 96 },

    mV4: { marginVertical: 4 },
    mV8: { marginVertical: 8 },
    mV16: { marginVertical: 16 },
    mV24: { marginVertical: 24 },
    mV32: { marginVertical: 32 },
    mV40: { marginVertical: 40 },
    mV48: { marginVertical: 48 },
    mV64: { marginVertical: 64 },
    mV96: { marginVertical: 96 },

    mH4: { marginHorizontal: 4 },
    mH8: { marginHorizontal: 8 },
    mH16: { marginHorizontal: 16 },
    mH24: { marginHorizontal: 24 },
    mH32: { marginHorizontal: 32 },
    mH40: { marginHorizontal: 40 },
    mH48: { marginHorizontal: 48 },
    mH64: { marginHorizontal: 64 },
    mH96: { marginHorizontal: 96 },

    //////////////////////////////////////////////////
    m5: { margin: 5 },
    m10: { margin: 10 },
    m15: { margin: 15 },
    m20: { margin: 20 },
    m25: { margin: 25 },
    m30: { margin: 30 },
    m35: { margin: 35 },
    m40: { margin: 40 },
    m50: { margin: 50 },
    m60: { margin: 60 },
    m70: { margin: 70 },
    m80: { margin: 80 },
    m90: { margin: 90 },
    m100: { margin: 100 },

    mT5: { marginTop: 5 },
    mT10: { marginTop: 10 },
    mT15: { marginTop: 15 },
    mT20: { marginTop: 20 },
    mT25: { marginTop: 25 },
    mT30: { marginTop: 30 },
    mT35: { marginTop: 35 },
    mT40: { marginTop: 40 },
    mT50: { marginTop: 50 },
    mT60: { marginTop: 60 },
    mT70: { marginTop: 70 },
    mT80: { marginTop: 80 },
    mT90: { marginTop: 90 },
    mT100: { marginTop: 100 },

    mB5: { marginBottom: 5 },
    mB10: { marginBottom: 10 },
    mB15: { marginBottom: 15 },
    mB20: { marginBottom: 20 },
    mB25: { marginBottom: 25 },
    mB30: { marginBottom: 30 },
    mB35: { marginBottom: 35 },
    mB40: { marginBottom: 40 },
    mB45: { marginBottom: 45 },
    mB50: { marginBottom: 50 },
    mB60: { marginBottom: 60 },
    mB70: { marginBottom: 70 },
    mB80: { marginBottom: 80 },
    mB90: { marginBottom: 90 },
    mB100: { marginBottom: 100 },

    mL5: { marginLeft: 5 },
    mL10: { marginLeft: 10 },
    mL15: { marginLeft: 15 },
    mL20: { marginLeft: 20 },
    mL25: { marginLeft: 25 },
    mL30: { marginLeft: 30 },
    mL35: { marginLeft: 35 },
    mL40: { marginLeft: 40 },
    mL50: { marginLeft: 50 },
    mL60: { marginLeft: 60 },
    mL70: { marginLeft: 70 },
    mL80: { marginLeft: 80 },
    mL90: { marginLeft: 90 },
    mL100: { marginLeft: 100 },

    mR5: { marginRight: 5 },
    mR10: { marginRight: 10 },
    mR15: { marginRight: 15 },
    mR20: { marginRight: 20 },
    mR25: { marginRight: 25 },
    mR30: { marginRight: 30 },
    mR35: { marginRight: 35 },
    mR40: { marginRight: 40 },
    mR50: { marginRight: 50 },
    mR60: { marginRight: 60 },
    mR70: { marginRight: 70 },
    mR80: { marginRight: 80 },
    mR90: { marginRight: 90 },
    mR100: { marginRight: 100 },

    mV5: { marginVertical: 5 },
    mV10: { marginVertical: 10 },
    mV15: { marginVertical: 15 },
    mV20: { marginVertical: 20 },
    mV25: { marginVertical: 25 },
    mV30: { marginVertical: 30 },
    mV35: { marginVertical: 35 },
    mV40: { marginVertical: 40 },
    mV50: { marginVertical: 50 },
    mV60: { marginVertical: 60 },
    mV70: { marginVertical: 70 },
    mV80: { marginVertical: 80 },
    mV90: { marginVertical: 90 },
    mV100: { marginVertical: 100 },

    mH5: { marginHorizontal: 5 },
    mH10: { marginHorizontal: 10 },
    mH15: { marginHorizontal: 15 },
    mH20: { marginHorizontal: 20 },
    mH25: { marginHorizontal: 25 },
    mH30: { marginHorizontal: 30 },
    mH35: { marginHorizontal: 35 },
    mH40: { marginHorizontal: 40 },
    mH50: { marginHorizontal: 50 },
    mH60: { marginHorizontal: 60 },
    mV70: { marginHorizontal: 70 },
    mV80: { marginHorizontal: 80 },
    mV90: { marginHorizontal: 90 },
    mH100: { marginHorizontal: 100 },

    ////////////////////////////////////////////

    txAlignC: { textAlign: "center" },
    txAlignJ: { textAlign: "justify" },
    txAlignR: { textAlign: "right" },
    txAlignL: { textAlign: "left" },

    bold: { fontWeight: "bold", },
    bold4: { fontWeight: "400", },
    bold5: { fontWeight: "500", },
    bold6: { fontWeight: "600", },
    bold7: { fontWeight: "700", },
    strick: { textDecorationLine: 'line-through' },
    underline: { textDecorationLine: "underline" },

    heading: { fontSize: 24, fontFamily: 'Lato-Bold' },

    tx9: { fontSize: 9, fontStyle: "normal", fontFamily: 'Lato-Regular' },
    tx10: { fontSize: 10, fontStyle: "normal", fontFamily: 'Lato-Regular' },
    tx11: { fontSize: 11, fontStyle: "normal", fontFamily: 'Lato-Regular' },
    tx12: { fontSize: 12, fontStyle: "normal", fontFamily: 'Lato-Regular' },
    tx14: { fontSize: 14, fontStyle: "normal", fontFamily: 'Lato-Regular' },
    tx16: { fontSize: 16, fontStyle: "normal", fontFamily: 'Lato-Regular' },
    tx18: { fontSize: 18, fontStyle: "normal", fontFamily: 'Lato-Regular' },
    tx20: { fontSize: 20, fontStyle: "normal", fontFamily: 'Lato-Regular' },
    tx22: { fontSize: 22, fontStyle: "normal", fontFamily: 'Lato-Regular' },
    tx24: { fontSize: 24, fontStyle: "normal", fontFamily: 'Lato-Regular' },
    tx26: { fontSize: 26, fontStyle: "normal", fontFamily: 'Lato-Regular' },
    tx28: { fontSize: 28, fontStyle: "normal", fontFamily: 'Lato-Regular' },
    tx30: { fontSize: 30, fontStyle: "normal", fontFamily: 'Lato-Regular' },
    tx36: { fontSize: 36, fontStyle: "normal", fontFamily: 'Lato-Regular' },

    row: { flexDirection: "row", },
    row_R: { flexDirection: "row-reverse", },
    column: { flexDirection: "column", },
    column_R: { flexDirection: "column-reverse", },

    justify_al_C: { justifyContent: "center", alignItems: "center", },

    justify_C: { justifyContent: "center", },
    justify_A: { justifyContent: "space-around", },
    justify_B: { justifyContent: "space-between", },

    alignI_C: { alignItems: "center", },
    alignI_FE: { alignItems: "flex-end", },
    alignI_FS: { alignItems: "flex-start", },
    alignI_S: { alignItems: "stretch", },

    alignS_C: { alignSelf: "center", },
    alignS_FE: { alignSelf: "flex-end", },
    alignS_FS: { alignSelf: "flex-start", },
    alignS_S: { alignSelf: "stretch", },

    B_colorP: { borderColor: '#E6B363' },
    B_colorS: { borderColor: '#304465' },
    B_colorT: { borderColor: '#BDBDBD' },
    B_colorW: { borderColor: '#FFF' },

    border: { borderWidth: 1 },
    border_B: { borderBottomWidth: 1 },
    border_T: { borderTopWidth: 1 },
    border_L: { borderLeftWidth: 1 },
    border_R: { borderRightWidth: 1 },

    Radius: { borderRadius: 10 },

    Radius_T_L: { borderTopLeftRadius: 10 },
    Radius_T_R: { borderTopRightRadius: 10 },
    Radius_B_L: { borderBottomLeftRadius: 10 },
    Radius_B_R: { borderBottomRightRadius: 10 },

    bordercolor: { borderColor: "#fff" },
    bordercolor_B: { borderBottomColor: "#fff" },
    bordercolor_T: { borderTopColor: "#fff" },
    bordercolor_L: { borderLeftColor: "#fff" },
    bordercolor_R: { borderRightColor: "#fff" },

    border_R: { borderRadius: 10, borderWidth: 1 },

    card1: {
        marginTop: -35,
        backgroundColor: "#ffffff",
        padding: 16,
        borderRadius: 10,
        marginHorizontal: 16,
        marginVertical: 8,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 5,
        },
        shadowOpacity: 0.2,
        shadowRadius: 10.32,
        elevation: 10,
    },
    card: {
        backgroundColor: "#ffffff",
        padding: 16,
        borderRadius: 10,
        marginHorizontal: 20,
        marginVertical: 10,

        shadowColor: "rgba(0,0,0,0.3)",
        shadowOffset: {
            width: 0,
            height: 5,
        },
        shadowOpacity: 0.34,
        shadowRadius: 6.27,
        elevation: 10,
    },
    shadow: {
        shadowColor: "rgba(0,0,0,0.3)",
        shadowOffset: {
            width: 0,
            height: 5,
        },
        shadowOpacity: 0.34,
        shadowRadius: 6.27,
        elevation: 10,
    },
    inputSearch: {
        height: 40,
        margin: -10,
        borderRadius: 5,
        color: "#c32a12",
    },
    inputgrey: {
        height: 50,
        paddingHorizontal: 16,
        alignItems: 'center',
        borderBottomColor: "#c32a12",
        borderBottomWidth: 1,
        borderRadius: 5,
        color: "#c32a12",
    },
    inputred: {
        height: 50,
        paddingHorizontal: 16,
        alignItems: 'center',
        borderBottomColor: "red",
        borderBottomWidth: 1,
        borderRadius: 5,
        color: "red",
    },
    inputRoundgrey: (focused) => ({
        height: 50,
        paddingHorizontal: 16,
        alignItems: 'center',
        borderColor: focused ? "#c62910" : "#999999",
        borderWidth: 0.7,
        borderRadius: 5,
        color: "#c32a12",
    }),
    inputRoundred: (focused) => ({
        height: 50,
        alignItems: 'center',
        paddingHorizontal: 16,
        borderColor: focused ? "#c62910" : "#EB5757",
        borderWidth: 1,
        borderRadius: 5,
        color: "#EB5757",
    }),

    success: {
        color: '#84E570',
        paddingHorizontal: 16,
        backgroundColor: "rgba(132, 229, 112, 0.3)",
        borderRadius: 200,
        fontSize: 12,
        fontFamily: 'Lato-Medium',
        alignSelf: 'center',
    },
    danger: {
        color: '#EB5757',
        paddingHorizontal: 8,
        backgroundColor: "rgba(235, 87, 87, 0.3)",
        borderRadius: 200,
        fontSize: 12,
        fontFamily: 'Lato-Medium',
        alignSelf: 'center',
    },
    info: {
        color: '#EEB61D',
        paddingHorizontal: 16,
        backgroundColor: "rgba(238, 182, 29, 0.3)",
        borderRadius: 200,
        fontSize: 12,
        fontFamily: 'Lato-Medium',
        alignSelf: 'center',
    },
    dark: {
        color: '#999999',
        paddingHorizontal: 16,
        backgroundColor: "rgba(153, 153, 153, 0.3)",
        borderRadius: 200,
        fontSize: 12,
        fontFamily: 'Lato-Medium',
        alignSelf: 'center',
    },
    fieldBoxLeft: {
        width: '80%',
        padding: 8,
        borderTopLeftRadius: 4,
        borderBottomLeftRadius: 4,
        borderWidth: 1,
        borderColor: '#999',
        borderRightWidth: 0,
        bordercolor: 'red'
    },
    fieldBoxRight: {
        alignItems: "center",
        width: '20%',
        padding: 8,
        borderColor: '#999',
        borderTopRightRadius: 4,
        borderBottomRightRadius: 4,
        borderWidth: 1,
        bordercolor: 'red'
    },

    LT: {
        fontFamily: 'Lato-Thin'
    },
    LM: {
        fontFamily: 'Lato-Medium'
    },
    LB: {
        fontFamily: 'Lato-Bold'
    },
    TIMER: {
        fontFamily: 'TickingTime'
    }
});
